version: '3.8'

services:
  exporter:
    build:
      context: ..
      dockerfile: demo/Dockerfile
    container_name: pg-bash-exporter
    ports:
      - "5252:5252"
    volumes:
      - ../configs/config.example.yaml:/etc/pg-bash-exporter/config.yaml

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.5.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - ./provisioning/dashboards/default.yml:/etc/grafana/provisioning/dashboards/default.yml
