version: '3.8'

services:
  exporter:
    build:
      context: ..
      dockerfile: demo/Dockerfile
    container_name: pg-bash-exporter
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../configs/config.example.yaml:/etc/pg-bash-exporter/config.yaml

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.5.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
